
## Getting and Cleaning Data Project




### This file explains how the script "run_analysis.R" works


#### The inputs of the script

* The data folder must be unzipped in the work directory
* The name of the data folder "UCI HAR Dataset" and subfolders are expected to stay unchanged

#### The ouput of the script

* The script produces a tidy data set with the file name : "tidy_data.txt" 
* The script saves the ouput file in the work directory.

#### how to execute the script in R?

1. Copy the the file  "run_analysis.R" in your work directory
2. in R console type : source("run_analysis.R")


#### The script sections 

**"run_analysis.R"  is divided into 6 parts as follows :**

- Part 1 : Reading Data sets : in this section the script reads all data sets from main data folder un subfolders.
- Part 2 : Merging the training and the test sets : in this section I prepare training and test data sets for merging by : 
                * Replacing columns names with the features vector
                * Adding and renaming subjects and activities columns
                then I merge training and test data sets using **rbind()** fonction.
- Part 3 : Adding activity names: To add a descriptive activity names to the data set, I start by renaming                         variables in "activity_labels" set and then use the "plyr" library to do a left join with the full dada set and the activity labels set.  
        I prefered the join() fonction in the "plyr" library because it keeps the original sorting.
- Part 4: Keeping only the Mean and Std for each measurement : I put in a vector columns names that contain the words "mean" & "std", I subset the data with this vector, then I remove columns names that contain "meanFreq"  which I think does not relate to this assignment.
- Part 5: Renaming variables : I use the gsub() fonction to make variables names more descriptive.
_ Part 6: Creates a second, independent tidy data set : I use aggregate() fonction to calculate the average of each variable for each activity and each subject, then I save the data to the file "tidy_data.txt".


##### For the code book see the file CodeBook.md